### ISSUE TITLE
移动端 vh 100

### ISSUE THREAD

**Issue by sunman7** [sunman7/my-blog#26]
### 移动端 100vh 问题

在移动端使用 100vh 时，发现在 Chrome、Safari 浏览器中，因为浏览器栏和一些导航栏、链接栏导致不一样的呈现：

你以为的 100vh === 视口高度

实际上 100vh === 视口高度 + 浏览器工具栏（地址栏等等）的高度

#### 解决方案

安装 vh-check `npm install vh-check --save`

```js
import vhCheck from 'vh-check';
vhCheck('browser-address-bar');

```

定义一个 CSS Mixin

```scss
@mixin vh($height: 100vh) {
  height: $height;
  height: calc(#{$height} - var(--browser-address-bar, 0px));
}

```

之后就是哪里不会点哪里。
